routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');

Route::get('/login', 'HomeController@login')->name('admin.login');
Route::post('/authenticate', 'HomeController@authenticate')->name('admin.authenticate');
Route::group(['middleware' => ['admin']], function () {
    Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('/changepass', 'HomeController@changepass')->name('admin.changepass');
    Route::get('/payment/pending', 'PaymentController@pending')->name('payment.pending');
    Route::get('/payment/paid-form/{id}', 'PaymentController@paid_form')->name('payment.paid.form');
    Route::post('/payment/paid-submit', 'PaymentController@paid_submit')->name('payment.paid.submit');
    Route::post('/payment/processing', 'PaymentController@processing')->name('payment.processing');
    Route::get('/payment/voucher-details/{id}', 'PaymentController@voucher_details')->name('payment.voucher-details');
    Route::get('/payment/voucher-download/{id}', 'PaymentController@download_pdf')->name('payment.voucher-download');
    Route::any('/payment/processing/list', 'PaymentController@processing_list')->name('payment.processing.list');
    Route::post('/checkpass', 'HomeController@checkpass')->name('admin.checkpass');
    Route::Resource('cities', 'CityController');
    Route::Resource('districts', 'DistrictController');
    Route::Resource('areas', 'AreaController');
    Route::resource('cats', 'CategoryController');
    Route::resource('subcats', 'SubcategoryController');
    Route::Resource('rider', 'RiderController');
    Route::get('/rider/assign/{id}/{area_id}', 'RiderController@show_need_assign')->name('admin.rider.assign');
    Route::post('/rider/assigned', 'RiderController@parcel_assigned')->name('admin.rider.assigned');
    // Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('logout', 'HomeController@logout')->name('admin.logout');
    Route::get('/parcel', 'ParcellController@index')->name('admin.parcel');
    Route::get('/parcel/change-status/{id}/{stage}/{extra}', 'ParcellController@change_status')->name('admin.parcel.change_status');
    Route::get('/parcel/show-status/{id}', 'ParcellController@show_status')->name('admin.parcel.show_status');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/home', function () {

//     return view('front.home');
// });

Route::get('/login', 'HomeController@login')->name('user.login');
Route::get('/', 'HomeController@home')->name('user.home');
Route::post('/authenticate', 'HomeController@authenticate')->name('user.authenticate');
Route::post('/signupotp', 'HomeController@signupotp')->name('user.signupotp');
Route::post('/checkotp', 'HomeController@checkotp')->name('user.checkotp');
Route::get('/faq', 'HomeController@faq')->name('user.faq');
Route::get('/policy', 'HomeController@policy')->name('user.policy');
Route::get('/coverage', 'HomeController@coverage')->name('user.coverage');
Route::get('/terms', 'HomeController@terms')->name('user.terms');
Route::group(['middleware' => ['user']], function () {

    Route::get('/logout', 'HomeController@logout')->name('user.logout');
    Route::get('/changepass', 'HomeController@changepass')->name('user.changepass');
    Route::post('/changepass/submit', 'HomeController@changepass_submit')->name('user.changepass.submit');

    Route::get('/notifications', 'HomeController@notifications')->name('user.notifications');
    Route::post('/notifications/update/{id}', 'HomeController@notif_update')->name('user.notification.update');
    Route::get('parcels/view', 'ParcelController@view')->name('user.view');
    Route::get('payments', 'PaymentController@index')->name('payments.index');
    Route::get('payments/details', 'PaymentController@details')->name('payments.details');
    Route::get('payments/pdf', 'PaymentController@pdf')->name('payments.pdf');
    Route::get('qr-code', 'ParcelController@qrcode')->name('user.qrcode');

    Route::get('/shopsetup', 'ShopController@shopsetup')->name('user.shopsetup');
    Route::get('/shopsetup/subcat/{id}', 'ShopController@find_subcat')->name('user.subcat');
    Route::get('/shopsetup/subcity/{id}', 'ShopController@find_subcity')->name('user.subcity');
    Route::get('/shopsetup/subarea/{id}', 'ShopController@find_subarea')->name('user.subarea');
    Route::resource('shops', 'ShopController');
    Route::resource('pickups', 'PickupController');
    Route::resource('paymethods', 'PaymethodController');
    Route::resource('parcels', 'ParcelController');
    Route::get('/parcels/label/{id}', 'ParcelController@label_download')->name('user.label.download');
    Route::get('/parcels/issue/{id}', 'ParcelController@issue')->name('user.issue');
    Route::get('/parcels/track/{id}', 'ParcelController@track_parcel')->name('user.track');
    Route::post('/parcels/track/', 'ParcelController@track_search')->name('user.track.submit');
    Route::get('/parcels/weightcharge/{id}', 'ParcelController@weight_charge')->name('user.weight.charge');
    Route::get('/parcels/areacharge/{id}', 'ParcelController@area_charge')->name('user.area.charge');
    Route::get('shops/activate/{id}', 'ShopController@activate')->name('shops.activate');

    Route::get('/merchants', 'MerchantController@dashboard')->name('merchant.dashboard');

});

app/Models/Shop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shop extends Model
{
    use HasFactory;
}

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Models\Area;
use App\Models\Category;
use App\Models\City;
use App\Models\District;
use App\Models\Notification;
use App\Models\Shop;
use App\Models\Subcategory;
use Auth;
use Illuminate\Http\Request;
use Validator;

class ShopController extends Controller
{

    public function index()
    {
        $shops = Shop::where('user_id', Auth::user()->id)->get();
        return view('front.shops.index', compact('shops'));

    }

    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), [ // <---
            's_name' => 'required',
        ]);
        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();

        }
        $priority = Shop::where('user_id', Auth::user()->id)->count();
        // dd($priority);
        switch ($priority) {
            case 0:
                $priority = 1;
                $status = '1';
                break;
            default:
                $priority = $priority + 1;
                $status = '0';

        }
        $shop = new Shop();
        $shop->shop_type = $request->s_type;
        $shop->user_id = Auth::user()->id;
        $shop->priority = $priority;
        $shop->status = $status;
        $shop->shop_name = $request->s_name;
        $shop->owner_name = $request->name;
        $shop->shop_email = $request->s_email;
        $shop->shop_address = $request->s_address;
        $shop->pickup_address = $request->p_address;
        $shop->pickup_area = $request->p_full_area;
        $shop->other_pickups = $request->p_full_area;
        $shop->pickup_phone = $request->p_phone;
        $shop->product_cat = $request->p_cat;
        $shop->product_subcat = $request->p_subcat;
        if ($shop->save()) {
            $notif = new Notification();
            $notif->shop_id = $shop->id;
            $notif->number = $request->p_phone;
            $notif->email = $request->s_email;
            if ($notif->save()) {
                toast('Shop creation success', 'success');
                return redirect('merchants');
            }

        } else {
            toast('Wrong details!', 'error');
            return back()->withInput();
        }

    }
    public function edit($id)
    {
        $dist = District::all();
        $cats = Category::all();
        $shop = Shop::findOrFail($id);
        return view('front.shops.edit', compact('shop', 'cats', 'dist'));

    }

    public function update(Request $request, $id)
    {
        $shop = Shop::findOrFail($id);
        if ($shop) {
            $shop->shop_name = $request->shop_name;
            $shop->shop_address = $request->shop_address;
            $shop->shop_email = $request->shop_email;
            if ($shop->save()) {
                toast('Shop Updated successfully', 'success');
                return redirect('shops');
            } else {
                toast('Wrong details!', 'error');
                return redirect('shops');
            }

        }

    }

    public function activate($id)
    {
        //pooor coding here
        $shop_status = Shop::where('user_id', Auth::user()->id)
            ->update(['status' => '0']);
        $shop_status2 = Shop::where('id', $id)
            ->update(['status' => '1']);
        toast('New shop activated', 'success');
        return redirect('merchants');

    }

    public function shopsetup()
    {
        $dist = District::all();
        $cats = Category::all();
        return view('front.shops.shop', compact('cats', 'dist'));
    }

    public function find_subcat($id)
    {
        $datas = Subcategory::where('cat_id', $id)->select('sub_cat_name as name', 'id')->get();
        return view('front.helpers.dropdown', compact('datas'));

    }
    public function find_subcity($id)
    {
        $datas = City::where('district_id', $id)->get();
        return view('front.helpers.dropdown', compact('datas'));

    }
    public function find_subarea($id)
    {
        $datas = Area::where('city_id', $id)->get();
        return view('front.helpers.dropdown', compact('datas'));

    }

}

resources/views/front/shops/create.blade.php
@extends('front.raftmaster')
@section('main')




@endsection

resources/views/front/shops/edit.blade.php
@extends('front.raftmaster')
@section('main')


<div id="shop_edit">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <div class="edit_top">
                    <h1>Edit Shop</h1> <span> <a href="{{route('shops.index')}}"><i class="far fa-times-circle"></i></a> </span>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-10 col-12">
                <div class="row">
                    <div class="col-12">
                        <form id="basic-form" method="post" action="{{route('shops.update',$shop->id)}}">

                            <input name="_method" type="hidden" value="PATCH">
                            @csrf
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="shopEmail">Shop Email</label>
                                    <input type="email" required class="form-control" value="{{$shop->shop_email}}" name="email" placeholder="Shop Email" id="shopEmail">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="address">Shop Address</label>
                                    <input type="text" required class="form-control" value="{{$shop->shop_address}}" name="shop_address" placeholder="Shop Address" id="address">
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="shopName">Shop Name</label>
                                    <input type="text" required value="{{$shop->shop_name}}" class="form-control" id="shopName" name="shop_name" placeholder="Shop Name">
                                </div>                                                       
                            </div>    
                            <p><i class="fas fa-exclamation-circle"></i> Pickup locations for this shop cannot be edited here <a href="#">Go to Pickup Location</a> </p>    
                            <div class="form-row justify-content-center">
                                <div class="form-group col-md-6 text-center">
                                <button class="text-center justify-content-center" type="submit">শপ এডিট করুন</button>
                                </div>                                                       
                            </div>         
                           
                        </form>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>














<div class="row mt-3 p-5 " style="display: none;">
    <div class="col-md-8 offset-md-2 mt-5 py-5" style="background-color:rgba(255, 255, 255,0.3); border-radius:5px">
        <h4 style="text-transform:none">Add Your Business Information</h3>
            <p>If you have more than one business, You can create multiple shop later.</p>
            <form role="form" id="quickForm" method="post" action="{{route('shops.store')}}">
                @csrf
                <div class="row">
                    <div class="col-12">

                    </div>



                </div>

                <div class="col-12">
                    <div class="row">
                        <div class="col-6">
                            <div class="form-group">
                                <label for="exampleInputPassword1">Reason for opening an account?
                                </label>
                                <select class="form-control" id="exampleFormControlSelect1" name="s_type" required>
                                    <option disabled selected value>choose an option</option>
                                    <option value="business">Business Use</option>
                                    <option value="personal">Personal use</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlInput1">Shop name</label>
                                <input type="text" class="form-control" value="shop_name" name="s_name" required id=""
                                    placeholder="shop name here..">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlInput1">Shop address</label>
                                <input type="text" class="form-control" name="s_address" required id=""
                                    placeholder="shop address here..">
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Pickup address</label>
                                <input type="text" class="form-control" name="p_address" required id=""
                                    placeholder="detail pick up address">
                            </div>

                        </div>
                        <div class="col-6">
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Shop email</label>
                                <input type="email" class="form-control" id="s_email" name="s_email" required
                                    placeholder="name@example.com">
                            </div>

                            <div class="form-group">
                                <label for="exampleFormControlInput1">Product type</label>
                                <select name="p_cat" class="form-control" id="p_cat" style="width: 100%;" required>
                                    <option disabled selected value>choose an option</option>
                                    @foreach($cats as $key=> $cat)
                                    <option value="{{$cat->id}}">{{$cat->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Product subcategory type</label>
                                <select name="p_subcat" class="form-control " id="p_subcat" style="width: 100%;"
                                    required>
                                    <option disabled selected value>choose an option</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="exampleFormControlInput1">Pickup Phone</label>
                                <input type="text" class="form-control" name="p_phone" required id=""
                                    placeholder="pick up mobile">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-12">
                    <div class="form-group">
                        <label for="exampleInputPassword1"> Select Pickup Area
                        </label>
                    </div>
                    <div class="row">

                        <div class="col">
                            <select class="form-control" id="p_dist" name="p_dist" required>
                                <option disabled selected value>--select District--</option>
                                @foreach($dist as $key=> $dist)
                                <option value="{{$dist->id}}">{{$dist->name}}</option>
                                @endforeach

                            </select>
                        </div>
                        <div class="col">
                            <select class="form-control" id="p_subcity" name="p_subcity" required>
                                <option disabled selected value>--select City--</option>

                            </select>
                        </div>
                        <div class="col">
                            <select class="form-control" id="p_subarea" name="p_subarea" required>
                                <option disabled selected value>--Select Area--</option>

                            </select>
                        </div>
                    </div>
                </div>

                <input type="hidden" class="form-control" id="p_full_area" name="p_full_area" placeholder="">

                <button type="submit" class="btn btn-primary">create Shop</button>
            </form>

    </div>

</div>

@endsection

@section('custom-js')
<script type="text/javascript">
    $('form').on('submit', function (e) {
        // validation code here

        $distvalue = $("#p_dist option:selected").text();
        $cityvalue = $("#p_subcity option:selected").text();
        $areavalue = $("#p_subarea option:selected").text();
        $('#p_full_area').val($distvalue + '>' + $cityvalue + '>' + $areavalue);

    });

    $('#p_cat').on('change', function () {
        $id = this.value;
        show_subcat($id);
    });
    $('#p_dist').on('change', function () {
        $id = this.value;
        show_subcity($id);
    });
    $('#p_subcity').on('change', function () {
        $id = this.value;
        show_subarea($id);
    });


    function show_subcat($id) {
        $.get("{{URL::to('shopsetup/subcat')}}/" + $id, function (data) {
            $('#p_subcat').html(data);

        });
    }

    function show_subcity($id) {
        $.get("{{URL::to('shopsetup/subcity')}}/" + $id, function (data) {
            $('#p_subcity').html(data);

        });
    }

    function show_subarea($id) {
        $.get("{{URL::to('shopsetup/subarea')}}/" + $id, function (data) {
            $('#p_subarea').html(data);

        });
    }

</script>
@endsection

resources/views/front/shops/index.blade.php
@extends('front.raftmaster')
@section('main')
{{-- your code here --}}






{{-- your code here --}}

<div id="shop_index">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <ul>
          <li class="first">
            <a href="{{ route('user.shopsetup')}}">
            <div class="add_shop">
              <div class="top">
              <i class="fas fa-plus-circle"></i>
              </div>
              <div class="bottom">
                <p>একটি নতুন শপ যুক্ত করুন</p>
              </div>
            </div>
            </a>
            
          </li>
          @foreach($shops as $key=>$shop)

          <li>
            <a href="{{route('shops.activate',$shop->id)}}">
              <div class="shop_item">
                <div class="item_top">
                  <h4>{{$shop->shop_name}}</h4>
                  <p>{{$shop->shop_address}}</p>
                  <p>{{$shop->pickup_phone}}</p>
                </div>
                <div class="item_bottom">
                  @if($shop->status =='1')
                  <div class="left">
                  <i class="fas fa-check"></i>
                  </div>
                  @endif
                  <div class="right">
                  <a  href="{{route('shops.edit',$shop->id)}}"><i class="fas fa-edit"></i></a>
                  </div>
                </div>
              </div>
            </a>
              
          </li>
          @endforeach
         
        </ul>
      </div>
    </div>
  </div>
</div>















<div class="row mt-5 p-5 " style="display:none;">
    @foreach($shops as $key=>$shop)
    <div class="col-sm-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title c-b" >{{$shop->shop_name}}</h5>
          <p class="card-text c-b">{{$shop->shop_address}}</p>
          @if($shop->status =='1')
          <a href="{{route('shops.activate',$shop->id)}}" class="btn-sm btn-success">Working..</a>
          @else
          <a href="{{route('shops.activate',$shop->id)}}" class="btn-sm btn-primary">Activate</a>
          @endif
          <a href="{{route('shops.edit',$shop->id)}}" class="btn-sm btn-warning">edit</a>
        </div>
      </div>
    </div>
    @endforeach
      <div class="col-sm-3">
        <div class="card">
          <div class="card-body">
           
            <p class="card-text c-b">Add new shop to grow your business</p>
            <p class="card-text c-b"></p>
            <a href="{{ route('user.shopsetup')}}"  class="btn-lg btn-danger">Add More</a> 
          </div>
        </div>
      </div>
  </div> 
@endsection