routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');

Route::get('/login', 'HomeController@login')->name('admin.login');
Route::post('/authenticate', 'HomeController@authenticate')->name('admin.authenticate');
Route::group(['middleware' => ['admin']], function () {
    Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('/changepass', 'HomeController@changepass')->name('admin.changepass');
    Route::get('/payment/pending', 'PaymentController@pending')->name('payment.pending');
    Route::get('/payment/paid-form/{id}', 'PaymentController@paid_form')->name('payment.paid.form');
    Route::post('/payment/paid-submit', 'PaymentController@paid_submit')->name('payment.paid.submit');
    Route::post('/payment/processing', 'PaymentController@processing')->name('payment.processing');
    Route::get('/payment/voucher-details/{id}', 'PaymentController@voucher_details')->name('payment.voucher-details');
    Route::get('/payment/voucher-download/{id}', 'PaymentController@download_pdf')->name('payment.voucher-download');
    Route::any('/payment/processing/list', 'PaymentController@processing_list')->name('payment.processing.list');
    Route::post('/checkpass', 'HomeController@checkpass')->name('admin.checkpass');
    Route::Resource('cities', 'CityController');
    Route::Resource('districts', 'DistrictController');
    Route::Resource('areas', 'AreaController');
    Route::resource('cats', 'CategoryController');
    Route::resource('subcats', 'SubcategoryController');
    Route::Resource('rider', 'RiderController');
    Route::get('/rider/assign/{id}/{area_id}', 'RiderController@show_need_assign')->name('admin.rider.assign');
    Route::post('/rider/assigned', 'RiderController@parcel_assigned')->name('admin.rider.assigned');
    // Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('logout', 'HomeController@logout')->name('admin.logout');
    Route::get('/parcel', 'ParcellController@index')->name('admin.parcel');
    Route::get('/parcel/change-status/{id}/{stage}/{extra}', 'ParcellController@change_status')->name('admin.parcel.change_status');
    Route::get('/parcel/show-status/{id}', 'ParcellController@show_status')->name('admin.parcel.show_status');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/home', function () {

//     return view('front.home');
// });

Route::get('/login', 'HomeController@login')->name('user.login');
Route::get('/', 'HomeController@home')->name('user.home');
Route::post('/authenticate', 'HomeController@authenticate')->name('user.authenticate');
Route::post('/signupotp', 'HomeController@signupotp')->name('user.signupotp');
Route::post('/checkotp', 'HomeController@checkotp')->name('user.checkotp');
Route::get('/faq', 'HomeController@faq')->name('user.faq');
Route::get('/policy', 'HomeController@policy')->name('user.policy');
Route::get('/coverage', 'HomeController@coverage')->name('user.coverage');
Route::get('/terms', 'HomeController@terms')->name('user.terms');
Route::group(['middleware' => ['user']], function () {

    Route::get('/logout', 'HomeController@logout')->name('user.logout');
    Route::get('/changepass', 'HomeController@changepass')->name('user.changepass');
    Route::post('/changepass/submit', 'HomeController@changepass_submit')->name('user.changepass.submit');

    Route::get('/notifications', 'HomeController@notifications')->name('user.notifications');
    Route::post('/notifications/update/{id}', 'HomeController@notif_update')->name('user.notification.update');
    Route::get('parcels/view', 'ParcelController@view')->name('user.view');
    Route::get('payments', 'PaymentController@index')->name('payments.index');
    Route::get('payments/details', 'PaymentController@details')->name('payments.details');
    Route::get('payments/pdf', 'PaymentController@pdf')->name('payments.pdf');
    Route::get('qr-code', 'ParcelController@qrcode')->name('user.qrcode');

    Route::get('/shopsetup', 'ShopController@shopsetup')->name('user.shopsetup');
    Route::get('/shopsetup/subcat/{id}', 'ShopController@find_subcat')->name('user.subcat');
    Route::get('/shopsetup/subcity/{id}', 'ShopController@find_subcity')->name('user.subcity');
    Route::get('/shopsetup/subarea/{id}', 'ShopController@find_subarea')->name('user.subarea');
    Route::resource('shops', 'ShopController');
    Route::resource('pickups', 'PickupController');
    Route::resource('paymethods', 'PaymethodController');
    Route::resource('parcels', 'ParcelController');
    Route::get('/parcels/label/{id}', 'ParcelController@label_download')->name('user.label.download');
    Route::get('/parcels/issue/{id}', 'ParcelController@issue')->name('user.issue');
    Route::get('/parcels/track/{id}', 'ParcelController@track_parcel')->name('user.track');
    Route::post('/parcels/track/', 'ParcelController@track_search')->name('user.track.submit');
    Route::get('/parcels/weightcharge/{id}', 'ParcelController@weight_charge')->name('user.weight.charge');
    Route::get('/parcels/areacharge/{id}', 'ParcelController@area_charge')->name('user.area.charge');
    Route::get('shops/activate/{id}', 'ShopController@activate')->name('shops.activate');

    Route::get('/merchants', 'MerchantController@dashboard')->name('merchant.dashboard');

});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\city;
use App\Models\District;
use Illuminate\Http\Request;
use Validator;

class CityController extends Controller
{
    public function index()
    {$r = new City;
        $city = District::orderBy('districts.created_at', 'desc')
            ->rightJoin('cities', 'cities.District_id', '=', 'districts.id')
            ->select('districts.name as d_name', 'districts.id as d_id', 'cities.name as c_name', 'cities.id as c_id')->paginate(10);
        return view('admin.city.index', compact('city'));
    }

    public function create()
    {
        $dist = District::all();
        return view('admin.city.create', compact('dist'));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [ // <---
            'name' => 'required',
        ]);
        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();

        }
        $city = new City();
        $city->district_id = $request->dist_id;
        $city->name = $request->name;
        if ($city->save()) {
            toast('Successfully Saved', 'success');
            return Redirect()->route('cities.index');
        } else {
            toast('Wrong Details', 'error');
            return Redirect()->back()->withInputes();
        }

    }

    public function edit($id)
    {
        $dist = District::all();
        $city = City::findOrFail($id);
        return view('admin.city.edit', compact('dist', 'city'));
    }
    public function update(Request $request, $id)
    {
        $city = City::findOrFail($id);
        $city->district_id = $request->dist_id;
        $city->name = $request->name;
        if ($city->save()) {
            toast('Successfully Updated', 'success');
            return Redirect()->route('cities.index');
        } else {
            toast('Wrong Details', 'error');
            return Redirect()->back()->withInputes();
        }

    }

    public function destroy($id)
    {
        if (city::destroy($id)) {
            toast('Successfully Deleted', 'success');
            return redirect()->route('cities.index');
        } else {
            toast('Wrong Details', 'error');
            return back();
        }
    }
}

resources/views/admin/city/create.blade.php
 <!-- jquery validation -->
 <div class="card card-primary">
  <div class="card-header">
    <h3 class="card-title">Setup City Details<small></small></h3>
  </div>
  <!-- /.card-header -->
  <!-- form start -->
<form role="form" id="quickForm" method="post" action="{{route('cities.store')}}">
  @csrf
    <div class="card-body">
      <div class="form-group">
        <label>District</label>
        <select name="dist_id" class="form-control " style="width: 100%;">
          @foreach($dist as $key=> $dist)
        <option value="{{$dist->id}}">{{$dist->name}}</option>
          @endforeach
        </select>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">City Name</label>
        <input type="text" name="name" class="form-control" required id="exampleInputEmail1" placeholder="Enter City Name">
      </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <button type="submit" onclick="checkValidate()" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>
<script type="text/javascript">
function checkValidate(){
  $('#quickForm').validate({
    rules: {
      email: {
        required: true,
        email: true,
      },
      password: {
        required: true,
        minlength: 5
      },
      terms: {
        required: true
      },
    },
    messages: {
      name: {
          required: "Please enter a name",
         
        },
        category: {
          required: "Please select a category",
         
        },
      terms: "Please accept our terms"
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
}

</script>

resources/views/admin/city/edit.blade.php
 <!-- jquery validation -->

 <div class="card card-primary">

    <div class="card-header">

      <h3 class="card-title">Edit City Details<small></small></h3>

    </div>

    <!-- /.card-header -->

    <!-- form start -->

  <form role="form" id="quickForm" method="post" action="{{route('cities.update',$city->id)}}">

    <input name="_method" type="hidden" value="PATCH">

    @csrf

      <div class="card-body">
        
        <div class="form-group">
          <label>District</label>
          <select name="dist_id" class="form-control " style="width: 100%;">
            @foreach($dist as $key=> $dist)
          <option {{$dist->id == $city->district_id ? "selected" : ""}} value="{{$dist->id}}">{{$dist->name}}</option>
            @endforeach
          </select>
        </div>

        <div class="form-group">

          <label for="exampleInputEmail1">City Name</label>

        <input type="text" required name="name" value="{{$city->name}}" class="form-control" id="exampleInputEmail1" placeholder="Enter Category Name">

        </div>



      </div>

  

     

      <!-- /.card-body -->

      <div class="card-footer">

        <button type="submit" onclick="checkValidate()" class="btn btn-primary">Submit</button>

      </div>

    </form>

  </div>

  

  <script type="text/javascript">

  function checkValidate(){

    $('#quickForm').validate({

      rules: {

        email: {

          required: true,

          email: true,

        },

        password: {

          required: true,

          minlength: 5

        },

        terms: {

          required: true

        },

      },

      messages: {

        name: {

          required: "Please enter a name",

         

        },

        category: {

          required: "Please select a category",

         

        },

        terms: "Please accept our terms"

      },

      errorElement: 'span',

      errorPlacement: function (error, element) {

        error.addClass('invalid-feedback');

        element.closest('.form-group').append(error);

      },

      highlight: function (element, errorClass, validClass) {

        $(element).addClass('is-invalid');

      },

      unhighlight: function (element, errorClass, validClass) {

        $(element).removeClass('is-invalid');

      }

    });

  }

  

  </script>

resources/views/admin/city/index.blade.php
@extends('admin.master')
@section('main')
<div class="row">
  <div class="col-12">
     <!-- jquery validation -->
 
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">City List</h3>

        <div class="card-tools">
          
        <a href="javascript:void(0)" onclick="show_agent_modal('{{route('cities.create')}}')" class="btn btn-md btn-primary">Add New City</a>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr class="footable-header">
            <th class="footable-first-visible" style="display: table-cell;">#</th>
            <th width="20%">Distrct Name</th>
            <th width="20%">City</th>
            <th>Options</th>
          </tr>
        </thead>
          <tbody>
            @foreach($city as $key=> $city)
            <tr>
              <td>{{$key+1}}</td>
            <td>{{$city->d_name}}</td>
            <td>{{$city->c_name}}</td>
              <td>
                <div class="btn-group">
                  <a href="javascript:void(0)" onclick="show_agent_modal('{{route('cities.edit',$city->c_id)}}')" class=" btn btn-outline btn-info "><i class="fas fa-edit"></i></a>
                  <a href="javascript:void(0)" onclick="confirm_modal('{{route('cities.destroy',$city->c_id)}}')" class=" btn btn-outline btn-danger btn-md "><i class="fa fa-trash"></i></a>

              
              </div>
              </td>
             
              
            </tr>
            @endforeach
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
      <div class="card-footer clearfix">
        <ul class="pagination pagination-sm m-0 float-right">
          {{-- {!! $city->links() !!} --}}
        </ul>
      </div>
    </div>
    <!-- /.card -->
  </div>
</div>
<div class="modal fade" id="category_modal">
  <div class="modal-dialog">
    <div id="modal_content" class="modal-content ">
    
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
@endsection

@section('customjs')
<script type="text/javascript">

  $(function () {
    //Initialize Select2 Elements
    $('.select2').select2()

    //Initialize Select2 Elements
    $('.select2bs4').select2({
      theme: 'bootstrap4'
    })
  });

  function show_agent_modal(dataUrl){
   
      $.get(dataUrl, function(data){
        
          $('#modal_content').html(data);
          $('#category_modal').modal('show', {backdrop: 'static'});
          setTimeout(function(){ 
            $('.select2').select2();
              $('.select2bs4').select2({
                theme: 'bootstrap4'
              })
           }, 1000);
      });
  }

 function checkValidate(){
  $('#quickForm').validate({
    rules: {
      email: {
        required: true,
        email: true,
      },
      password: {
        required: true,
        minlength: 5
      },
      terms: {
        required: true
      },
    },
    messages: {
      email: {
        required: "Please enter a email address",
        email: "Please enter a vaild email address"
      },
      password: {
        required: "Please provide a password",
        minlength: "Your password must be at least 5 characters long"
      },
      terms: "Please accept our terms"
    },
    errorElement: 'span',
    errorPlacement: function (error, element) {
      error.addClass('invalid-feedback');
      element.closest('.form-group').append(error);
    },
    highlight: function (element, errorClass, validClass) {
      $(element).addClass('is-invalid');
    },
    unhighlight: function (element, errorClass, validClass) {
      $(element).removeClass('is-invalid');
    }
  });
 }
 

</script>
@endsection