routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
// Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');

Route::get('/login', 'HomeController@login')->name('admin.login');
Route::post('/authenticate', 'HomeController@authenticate')->name('admin.authenticate');
Route::group(['middleware' => ['admin']], function () {
    Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('/changepass', 'HomeController@changepass')->name('admin.changepass');
    Route::get('/payment/pending', 'PaymentController@pending')->name('payment.pending');
    Route::get('/payment/paid-form/{id}', 'PaymentController@paid_form')->name('payment.paid.form');
    Route::post('/payment/paid-submit', 'PaymentController@paid_submit')->name('payment.paid.submit');
    Route::post('/payment/processing', 'PaymentController@processing')->name('payment.processing');
    Route::get('/payment/voucher-details/{id}', 'PaymentController@voucher_details')->name('payment.voucher-details');
    Route::get('/payment/voucher-download/{id}', 'PaymentController@download_pdf')->name('payment.voucher-download');
    Route::any('/payment/processing/list', 'PaymentController@processing_list')->name('payment.processing.list');
    Route::post('/checkpass', 'HomeController@checkpass')->name('admin.checkpass');
    Route::Resource('cities', 'CityController');
    Route::Resource('districts', 'DistrictController');
    Route::Resource('areas', 'AreaController');
    Route::resource('cats', 'CategoryController');
    Route::resource('subcats', 'SubcategoryController');
    Route::Resource('rider', 'RiderController');
    Route::get('/rider/assign/{id}/{area_id}', 'RiderController@show_need_assign')->name('admin.rider.assign');
    Route::post('/rider/assigned', 'RiderController@parcel_assigned')->name('admin.rider.assigned');
    // Route::get('/', 'HomeController@dashboard')->name('admin.dashboard');
    Route::get('logout', 'HomeController@logout')->name('admin.logout');
    Route::get('/parcel', 'ParcellController@index')->name('admin.parcel');
    Route::get('/parcel/change-status/{id}/{stage}/{extra}', 'ParcellController@change_status')->name('admin.parcel.change_status');
    Route::get('/parcel/show-status/{id}', 'ParcellController@show_status')->name('admin.parcel.show_status');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// Route::get('/home', function () {

//     return view('front.home');
// });

Route::get('/login', 'HomeController@login')->name('user.login');
Route::get('/', 'HomeController@home')->name('user.home');
Route::post('/authenticate', 'HomeController@authenticate')->name('user.authenticate');
Route::post('/signupotp', 'HomeController@signupotp')->name('user.signupotp');
Route::post('/checkotp', 'HomeController@checkotp')->name('user.checkotp');
Route::get('/faq', 'HomeController@faq')->name('user.faq');
Route::get('/policy', 'HomeController@policy')->name('user.policy');
Route::get('/coverage', 'HomeController@coverage')->name('user.coverage');
Route::get('/terms', 'HomeController@terms')->name('user.terms');
Route::group(['middleware' => ['user']], function () {

    Route::get('/logout', 'HomeController@logout')->name('user.logout');
    Route::get('/changepass', 'HomeController@changepass')->name('user.changepass');
    Route::post('/changepass/submit', 'HomeController@changepass_submit')->name('user.changepass.submit');

    Route::get('/notifications', 'HomeController@notifications')->name('user.notifications');
    Route::post('/notifications/update/{id}', 'HomeController@notif_update')->name('user.notification.update');
    Route::get('parcels/view', 'ParcelController@view')->name('user.view');
    Route::get('payments', 'PaymentController@index')->name('payments.index');
    Route::get('payments/details', 'PaymentController@details')->name('payments.details');
    Route::get('payments/pdf', 'PaymentController@pdf')->name('payments.pdf');
    Route::get('qr-code', 'ParcelController@qrcode')->name('user.qrcode');

    Route::get('/shopsetup', 'ShopController@shopsetup')->name('user.shopsetup');
    Route::get('/shopsetup/subcat/{id}', 'ShopController@find_subcat')->name('user.subcat');
    Route::get('/shopsetup/subcity/{id}', 'ShopController@find_subcity')->name('user.subcity');
    Route::get('/shopsetup/subarea/{id}', 'ShopController@find_subarea')->name('user.subarea');
    Route::resource('shops', 'ShopController');
    Route::resource('pickups', 'PickupController');
    Route::resource('paymethods', 'PaymethodController');
    Route::resource('parcels', 'ParcelController');
    Route::get('/parcels/label/{id}', 'ParcelController@label_download')->name('user.label.download');
    Route::get('/parcels/issue/{id}', 'ParcelController@issue')->name('user.issue');
    Route::get('/parcels/track/{id}', 'ParcelController@track_parcel')->name('user.track');
    Route::post('/parcels/track/', 'ParcelController@track_search')->name('user.track.submit');
    Route::get('/parcels/weightcharge/{id}', 'ParcelController@weight_charge')->name('user.weight.charge');
    Route::get('/parcels/areacharge/{id}', 'ParcelController@area_charge')->name('user.area.charge');
    Route::get('shops/activate/{id}', 'ShopController@activate')->name('shops.activate');

    Route::get('/merchants', 'MerchantController@dashboard')->name('merchant.dashboard');

});

app/Models/District.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    use HasFactory;
}

app/Http/Controllers/Admin/DistrictController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\District;
use Illuminate\Http\Request;
use Validator;

class DistrictController extends Controller
{
    public function index()
    {
        $dist = District::orderBy('created_at', 'desc')->paginate(10);
        return view('admin.district.index', compact('dist'));
    }

    public function create()
    {
        return view('admin.district.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [ // <---
            'name' => 'required',
        ]);
        if ($validator->fails()) {
            return back()->with('toast_error', $validator->messages()->all()[0])->withInput();

        }
        $dist = new District();
        $dist->name = $request->name;

        if ($dist->save()) {
            toast('Successfully Saved', 'success');
            return Redirect()->route('districts.index');
        } else {
            toast('Wrong Details', 'error');
            return Redirect()->back()->withInputes();
        }

    }
    public function edit($id)
    {
        $dist = District::findOrFail(base64_decode($id));
        return view('admin.district.edit', compact('dist'));
    }
    public function update(Request $request, $id)
    {
        $dist = District::findOrFail($id);
        $dist->name = $request->name;

        if ($dist->save()) {
            toast('Successfully Updated', 'success');
            return Redirect()->route('districts.index');
        } else {
            toast('wrong details', 'error');
            return Redirect()->back()->withInputes();
        }
        return Redirect()->route('districts.index');
    }

    public function destroy($id)
    {
        if (District::destroy(base64_decode($id))) {
            toast('Successfully Deleted', 'success');
            return redirect()->route('districts.index');
        } else {
            toast('Wrong Details', 'error');
            return back();
        }
    }
}

resources/views/admin/district/create.blade.php
<form method="post" action="{{ route('districts.store') }}">
    @csrf
    <div class="modal-header">
        <h5 class="modal-title">Add New District</h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>

    <div class="modal-body">
        <div class="form-group row">
            <div class="col-lg-12">
                <label>District <span style="color: red">&nbsp*</span></label>
                <input type="text" class="form-control border-teal" placeholder="Enter District" name="name" required>
            </div>
        </div>
        
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-link pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn bg-primary">Save District</button>
    </div>
    </div>
</form>

resources/views/admin/district/edit.blade.php
<form role="form" id="quickForm" method="post" action="{{route('districts.update',$dist->id)}}">

    <input name="_method" type="hidden" value="PATCH">
    @csrf
    <div class="modal-header">
        <h5 class="modal-title">Edit District</h5>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>

    <div class="modal-body">
        <div class="form-group row">
            <div class="col-lg-12">
                <label>District <span style="color: red">&nbsp*</span></label>
                <input type="text" class="form-control border-teal" placeholder="Enter District" value="{{$dist->name}}" name="name" required>
            </div>
        </div>
        
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-link pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn bg-primary">Update</button>
    </div>
    </div>
</form>

resources/views/admin/district/index.blade.php
@extends('admin.master')
@section('main')
<div class="row">
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Manage Districts</h3>

        <div class="card-tools">
         
            <div class="">
              <a href="javascript:void(0)" onclick="show_add_category_modal()" class="btn btn-md btn-primary">Add New District</a>
            </div>
          
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive p-0">
        <table class="table table-hover text-nowrap">
          <thead>
            <tr class="footable-header">
            <th class="footable-first-visible" style="display: table-cell;">#</th>
            <th width="30%" >District Name</th>
            <th>Options</th>
          </tr>
        </thead>
          <tbody>
            @foreach($dist as $key =>$dist)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td>{{$dist->name}}</td>
                                   
                                    <td>
                                        <div class="btn-group">
                                            <a href="javascript:void(0)" onclick="show_edit_category_modal('{{route('districts.edit', base64_encode($dist->id))}}')" class=" btn btn-outline btn-info "><i class="fas fa-edit"></i></a>
                                            
                                            <a href="javascript:void(0)" onclick="confirm_modal('{{route('districts.destroy',base64_encode($dist->id))}}')" class=" btn btn-outline btn-danger "> <i class="fas fa-trash"></i> </a>
                                        
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
            
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
</div>
<div class="modal fade" id="raft_modal">
    <div class="modal-dialog">
      <div id="modal_content" class="modal-content">
       
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
@endsection
@section('customjs')
<script type="text/javascript">
     function show_add_category_modal(){
        // $('#raft_modal').modal('show',{backdrop:'static'});
            $.get('{{ route('districts.create') }}', function(data){
             
                $('#modal_content').html(data);
                $('#raft_modal').modal('show',{backdrop:'static'});
            });
        }
        function show_edit_category_modal($url){
        // $('#raft_modal').modal('show',{backdrop:'static'});
            $.get($url, function(data){
             
                $('#modal_content').html(data);
                $('#raft_modal').modal('show',{backdrop:'static'});
            });
        }
</script>
@endsection